USE personasDB;

DROP TABLE CIUDADES;
DROP TABLE TIPO_DOCUMENTO;

CREATE TABLE CIUDADES(
	ID_CIUDAD INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL
);

CREATE TABLE TIPO_DOCUMENTO(
	ID_TIPO_DOCUMENTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(200) NOT NULL
);

CREATE TABLE DOCUMENTO(
	ID_DOCUMENTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NUMERO INT,
    ID_TIPO_DOCUMENTO INT NOT NULL,
	FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TIPO_DOCUMENTO(ID_TIPO_DOCUMENTO)
);

CREATE TABLE PERSONAS(
	ID_PERSONA  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRES VARCHAR(200) NOT NULL,
    APELLIDOS VARCHAR(200) NOT NULL,
    ID_DOCUMENTO INT NOT NULL UNIQUE,
    EDAD INT NOT NULL,
    ID_CIUDAD INT NOT NULL,
    ID_FOTO INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTO(ID_DOCUMENTO),
    FOREIGN KEY (ID_CIUDAD) REFERENCES CIUDADES(ID_CIUDAD)
    
);


